{"errorMessage": "Expecting value: line 1 column 1 (char 0)", "errorType": "JSONDecodeError", "requestId": "e8c71d80-1b73-4920-81cc-62a319dfbf46", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 55, in lambda_handler\n    response_payload = json.loads(response['Payload'].read().decode('utf-8'))\n", "  File \"/var/lang/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n", "  File \"/var/lang/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n", "  File \"/var/lang/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n"]}